name: Vendease E2E Tests

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    name: E2E and API tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress install
        uses: cypress-io/github-action@v6
        with:
          runTests: false

      - run: npx cypress info
      - run: node --version
      - run: node -p 'os.cpus()'
      - run: npm ci

      - name: Run Reqres Server API tests
        run: npm run test:api

      - name: Run Amazon.in E2E tests
        run: npm run test:e2e
