name: Vendease E2E Tests

on:
  push:

jobs:
  RunQDE2ETests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress install
        uses: cypress-io/github-action@v6
        with:
          runTests: false

      - run: npx cypress info
      - run: node --version
      - run: node -p 'os.cpus()'
      - run: npm ci

      - name: Run E2E tests
        run: npm run test:e2e
